name: lint the project

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install eslint
        run: npm install -g eslint@8.57.0
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run eslint
        run: pnpm eslint .
